/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RoleRouteImport } from './routes/role'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserNearbyRouteImport } from './routes/user.nearby'
import { Route as UserNavigationRouteImport } from './routes/user.navigation'
import { Route as DriverRegisterRouteImport } from './routes/driver.register'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverNavigationRouteImport } from './routes/driver.navigation'
import { Route as DriverLoginRouteImport } from './routes/driver.login'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserNearbyRoute = UserNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => UserRoute,
} as any)
const UserNavigationRoute = UserNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => UserRoute,
} as any)
const DriverRegisterRoute = DriverRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverNavigationRoute = DriverNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => DriverRoute,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/role': typeof RoleRoute
  '/user': typeof UserRouteWithChildren
  '/driver/history': typeof DriverHistoryRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/register': typeof DriverRegisterRoute
  '/user/navigation': typeof UserNavigationRoute
  '/user/nearby': typeof UserNearbyRoute
  '/user/profile': typeof UserProfileRoute
  '/driver/': typeof DriverIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/role': typeof RoleRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/register': typeof DriverRegisterRoute
  '/user/navigation': typeof UserNavigationRoute
  '/user/nearby': typeof UserNearbyRoute
  '/user/profile': typeof UserProfileRoute
  '/driver': typeof DriverIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/driver': typeof DriverRouteWithChildren
  '/role': typeof RoleRoute
  '/user': typeof UserRouteWithChildren
  '/driver/history': typeof DriverHistoryRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/register': typeof DriverRegisterRoute
  '/user/navigation': typeof UserNavigationRoute
  '/user/nearby': typeof UserNearbyRoute
  '/user/profile': typeof UserProfileRoute
  '/driver/': typeof DriverIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/driver'
    | '/role'
    | '/user'
    | '/driver/history'
    | '/driver/login'
    | '/driver/navigation'
    | '/driver/profile'
    | '/driver/register'
    | '/user/navigation'
    | '/user/nearby'
    | '/user/profile'
    | '/driver/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/role'
    | '/driver/history'
    | '/driver/login'
    | '/driver/navigation'
    | '/driver/profile'
    | '/driver/register'
    | '/user/navigation'
    | '/user/nearby'
    | '/user/profile'
    | '/driver'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/driver'
    | '/role'
    | '/user'
    | '/driver/history'
    | '/driver/login'
    | '/driver/navigation'
    | '/driver/profile'
    | '/driver/register'
    | '/user/navigation'
    | '/user/nearby'
    | '/user/profile'
    | '/driver/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriverRoute: typeof DriverRouteWithChildren
  RoleRoute: typeof RoleRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/nearby': {
      id: '/user/nearby'
      path: '/nearby'
      fullPath: '/user/nearby'
      preLoaderRoute: typeof UserNearbyRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/navigation': {
      id: '/user/navigation'
      path: '/navigation'
      fullPath: '/user/navigation'
      preLoaderRoute: typeof UserNavigationRouteImport
      parentRoute: typeof UserRoute
    }
    '/driver/register': {
      id: '/driver/register'
      path: '/register'
      fullPath: '/driver/register'
      preLoaderRoute: typeof DriverRegisterRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/navigation': {
      id: '/driver/navigation'
      path: '/navigation'
      fullPath: '/driver/navigation'
      preLoaderRoute: typeof DriverNavigationRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface DriverRouteChildren {
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverNavigationRoute: typeof DriverNavigationRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverRegisterRoute: typeof DriverRegisterRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverHistoryRoute: DriverHistoryRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverNavigationRoute: DriverNavigationRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverRegisterRoute: DriverRegisterRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface UserRouteChildren {
  UserNavigationRoute: typeof UserNavigationRoute
  UserNearbyRoute: typeof UserNearbyRoute
  UserProfileRoute: typeof UserProfileRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserNavigationRoute: UserNavigationRoute,
  UserNearbyRoute: UserNearbyRoute,
  UserProfileRoute: UserProfileRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriverRoute: DriverRouteWithChildren,
  RoleRoute: RoleRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
